site_name: SSE Documentation Example

nav:
    - Home: 'index.md'
    - 'User Guide':
      - Installation: 'compilation-and-installation.md'
      - Getting Started: 'how-to.md'

repo_url: https://github.com/constracktor/sse-mkdocs-exercise

site_author: Alexander Strack

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
